### ISSUE TITLE
Can i help?

### ISSUE THREAD

**Issue by julientaq** [Alecaddd/Akira#2]
Hey!

i'm a UX/UI designer/dev and i learnt about akira yesterday, as i was struggling about going back to osx coz i miss sketch.

And then i heard about akira UX.

So my question. How can i help? How can i beta test? How can I (write what you need here)

Grazie mille.

**Comment by Alecaddd** [comment]
Hi, thank you so much for this message 😄 
I wrote a post on my forum, I guess you already commented on that one. Right now I'm learning Vala and Gtk+, the base stack I decided to use to code Akira. 

I built a small SQL client app as an exercise, and I should release it soon on Elementary OS App Center. I'm having issues with the compiler and packaging the deb file, so it's taking longer than expected, but I kinda knew it was going to happen, that's why I started with a test and small app, so I can learn the right process and fix everything I need, instead of having these issues with Akira and needing to refactor a pretty big app.

The initial development of Akira should start in a week or two, and the first thing I want to do is to release a proper documentation to build it locally for testing. I will an updated on the forum every time there's a new version available. Early testing from many people will be crucial, so if you have a Linux OS, having your feedback would be amazing.

Thank you so much for your interest, did you check on the forum the UI I created for it? Let me know what do you think, and let's continue this conversation on the forum 👍

**Comment by julientaq** [comment]
Let's do that.
You could also put the links to the forum and the UI (nice ui though :D) in the readme on this github, so people who want to play ball will know where the field is.

Let's play together.
