### ISSUE TITLE
Qt

### ISSUE THREAD

**Issue by UKSFM99** [Alecaddd/Akira#33]
Please support QT?

**Comment by zangent** [comment]
What benefit would this gain from running with Qt?
Anyway, that's kind of a massive undertaking, so I doubt @Alecaddd would go through the effort of building Akira for GTK+ *and* Qt.

**Comment by theotix** [comment]
For multiplateform I suppose. 
Alessandro said he plan to dev Akira to be a linux app, not a multiplaform one.

**Comment by Alecaddd** [comment]
Hi, thanks for the request but I won't refactor the application in Qt. It's a completely different code base from Vala and I'm not planning to support Windows or MacOS, like ever 😃 
Just a native Linux app.
Cheers

**Comment by julientaq** [comment]
Not reopening the issue @alecaddd, but i want to give my two cents about that, because, if you dont support other OS (which i can understand without any issue) you need to be sure that you'll be able to support collaboration between OS and computers. 

The way i see it, we, linux designers, are put outside of the design game not only because the support for our beloved OSes is not there, it's also because the app dont let you share assets. I am curently in the situation where i need to set a working space for two designers using Mac and sketch, Windows designers using Adobe XD and  myself, going from figma to inkscape, to code svg to show animations. 

We're stuck. 

There is no options for now to work together first and foremost, because SVG is implemented partially in the different applications. It would be good, if the export and import of svg was made the right way so we could create some spaces for discussions between users, whatever tool they work with. 

This is the best way to show that linux and akira, are powerful tools, but are also friendly and open to others.

**Comment by zangent** [comment]
Probably, what'll end up happening is someone (either @Alecaddd or someone else just making a pull request) will add support for the filetypes of other design software. Probably not PSD, at least for a while, because it's a trainwreck, but afaik the `.sketch` format is just JSON, so it wouldn't be hard to support something like that. Linux exclusivity doesn't mean that the project can't play nice with everyone else.

**Comment by julientaq** [comment]
exactly my thoughts. 

But i'd rather have a complete svg export/import than just an import from sketch.
Especially with all those coming and already here apps: figma, invidion design. etc.

And at the same time, sketch being json, it should be easy.

**Comment by julientaq** [comment]
Go @Alecaddd !

**Comment by Alecaddd** [comment]
Ahaha, thanks, everyone.
I should probably start writing all these stuff into the Wiki of this repo, just to prevent future questions that I already answered.

I'll do that, sooner or later, right now, I'm struggling with SVG v2 in generating cone gradients....it's...so...painful 😭
